# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: devel
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_script: Rscript -e "install.packages('rsvg')"
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev
  - name: Strict Latin-1 locale
    r: release
    before_script:
      - sudo locale-gen en_US
      - export LC_ALL=en_US
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev
  - r: release
    name: tidyr-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev
  - r: release
    name: tibble-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/tibble')"
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev
  - r: release
    name: xpectr-devel
    before_script: Rscript -e "remotes::install_github('ludvigolsen/xpectr')"
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev
  - r: release
    name: multiple-devel
    before_script: Rscript -e "remotes::install_github(c('ludvigolsen/xpectr', 'r-lib/vctrs', 'tidyverse/tidyr', 'tidyverse/tibble', 'lme4/lme4'), dependencies = TRUE)"
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev
  - r: release
    os: osx
    brew_packages: imagemagick@6
    name: release osx
  - r: oldrel
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev
  - r: 3.5.0
    before_install:
    - sudo add-apt-repository -y ppa:cran/imagemagick
    - sudo apt-get update
    - sudo apt-get install -y libmagick++-dev

# The addon solution to installing imagemagick didn't work, so we install it
# manually on every ubuntu machine. Might work if we use later ubuntu distributions.
# We let the addon stay though. Just in case. Not sure if that's a bad idea.
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
  packages:
    - libmagick++-dev

