# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    name: tidyr-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
  - r: release
    os: osx
    brew_packages: imagemagick@6
    name: release osx
  - r: oldrel

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
  packages:
    - libmagick++-dev
    - librsvg2-dev
    - libwebp-dev
    - libpoppler-cpp-dev
    - libtesseract-dev
    - libleptonica-dev
    - tesseract-ocr-eng
    - r-cran-rgdal
    - libfftw3-dev
    - cargo
    - gsfonts

